name: Deploy nest.js to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH command
        uses: appleboy/ssh-action@master
        with:
          host:  ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22 
        script_timeout: 2m
          script: |
            cd /termin/backend_termin_calender
            git pull origin main
            npm install
            npm run build
            pm2 restart nest-app