name: Deploy nest.js to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Execute SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 5m  # Correct parameter name
          script: |
            cd /termin/backend_termin_calender
            git pull
            npm install
            npm run build
            pm2 delete termin-back-app || true
            pm2 start /termin/backend_termin_calender/dist/src/main.js --name "termin-back-app" --watch -- --port 4001
            pm2 save
            pm2 startup